baseURL = "https://aminakhshi.github.io/"
languageCode = "en-us"
title = "Amin Akhshi - Computational Scientist"
theme = "bootstrap-theme"

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[params]
  # Site parameters
  author = "Amin Akhshi"
  description = "Computational Scientist & Researcher"
  github = "https://github.com/aminakhshi"
  linkedin = "https://www.linkedin.com/in/amin-akhshi-9750541b6/"
  orcid = "https://orcid.org/0000-0002-6995-3884"
  email = "amin.akhshi@mail.mcgill.ca"
  location = "Montreal, Canada"
  
  # Enable features
  enableAnimations = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "#home"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "#about"
    weight = 2
  [[menu.main]]
    name = "Experience"
    url = "#experience"
    weight = 3
  [[menu.main]]
    name = "Education"
    url = "#education"
    weight = 4
  [[menu.main]]
    name = "Skills"
    url = "#skills"
    weight = 5
  [[menu.main]]
    name = "Projects"
    url = "#portfolio"
    weight = 6
  [[menu.main]]
    name = "Publications"
    url = "#publications"
    weight = 7
  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 8
